v<-c(1,2,3,4,5)
suma<-sum(v)
produs<-prod(v)
minim<-min(v)
maxim<-max(v)
media_aritmetica<-mean(v)
dimensiune_vector<-length(v)

cat("vectorul este ", v, "\n")
cat("suma elementelor vectorului este ", suma, "\n")
cat("produsul elementelor vectorului este ", produs, "\n")
cat("elementul minim este ", minim, "\n")
cat("elementul maxim este ", maxim, "\n")
cat("media aritmetica este ", media_aritmetica, "\n")
cat("dimensiunea vectorului este ", dimensiune_vector, "\n")